#!/bin/bash

# Resolve the script's path, handling symlinks
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "${SCRIPT_PATH}")"
DOCKERFILE=claude-container.Dockerfile
IMAGE_NAME=claude-container
DATA_DIR="${HOME}/ai-cli/claude"
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)
CURRENT_USER=$(whoami)

mkdir -p "${DATA_DIR}"
docker build -f "${SCRIPT_DIR}/${DOCKERFILE}" -t ${IMAGE_NAME} "${SCRIPT_DIR}"
docker run --rm -it \
  --user "${CURRENT_UID}:${CURRENT_GID}" \
  --volume "${PWD}:${PWD}"  \
  --volume "${DATA_DIR}:/home/user" \
  --workdir "${PWD}" \
  --env "HOME=/home/user" \
  ${IMAGE_NAME}