#!/bin/bash

# Resolve the script's path, handling symlinks
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "${SCRIPT_PATH}")"
DOCKERFILE=claude-container.Dockerfile
IMAGE_NAME=claude-container
DATA_DIR="${HOME}/claude-container"
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)

# handle special commands and remove used args
case "$1" in
  --build-container)
      echo "Rebuilding container..."
      shift
      docker build -f "${SCRIPT_DIR}/${DOCKERFILE}" -t ${IMAGE_NAME} "${SCRIPT_DIR}"
      ;;
  --rebuild-container)
      echo "Rebuilding container..."
      shift
      docker build -f "${SCRIPT_DIR}/${DOCKERFILE}" -t ${IMAGE_NAME} "${SCRIPT_DIR}" --no-cache --pull
      ;;
esac

# make local data dir
mkdir -p "${DATA_DIR}"

# build image only if it doesn't exist
if [ -z "$(docker images -q ${IMAGE_NAME} 2>/dev/null)" ]; then
  echo "Building ${IMAGE_NAME} image..."
  docker build -f "${SCRIPT_DIR}/${DOCKERFILE}" -t ${IMAGE_NAME} "${SCRIPT_DIR}"
fi

# start container with $DATA_DIR as Claude's user data and $PWD as current dir
docker run --rm -it \
  --user "${CURRENT_UID}:${CURRENT_GID}" \
  --volume "${PWD}:${PWD}"  \
  --volume "${DATA_DIR}:/home/user" \
  --workdir "${PWD}" \
  --env "HOME=/home/user" \
  ${IMAGE_NAME} \
  /usr/local/bin/claude "$@"
