services:
  gateway:
    build: ../gateway
    stop_grace_period: 5s
    volumes:
      - ../gateway/squid.conf:/etc/squid/squid.conf:ro
    networks:
      - public_net
      - private_net

  claude-code: &cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        NPM_PACKAGE: "@anthropic-ai/claude-code"
    profiles: ["cli"] # prevents auto-start with docker compose up
    networks:
      - private_net
    environment:
      https_proxy: http://gateway:3128
      http_proxy: http://gateway:3128
    depends_on:
      - gateway

  codex:
    <<: *cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        NPM_PACKAGE: "@openai/codex"

  gemini:
    <<: *cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        NPM_PACKAGE: "@google/gemini-cli"

  cline:
    <<: *cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        NPM_PACKAGE: cline
        POST_INSTALL_SCRIPT: |-
          npm install -g kanban

  opencode:
    <<: *cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        NPM_PACKAGE: opencode-ai

  aider:
    <<: *cli_tool
    build:
      context: .
      dockerfile: python.Dockerfile
      args:
        PIP_PACKAGE: aider-chat

  goose:
    <<: *cli_tool
    build:
      context: .
      dockerfile: debian.Dockerfile
      args:
        INSTALL_COMMAND: curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash

  pi:
    <<: *cli_tool
    build:
      context: .
      dockerfile: nodejs.Dockerfile
      args:
        INSTALL_COMMAND: |-
          npm install -g --ignore-scripts @earendil-works/pi-coding-agent
          pi install npm:pi-ask-user

networks:
  public_net:
    driver: bridge
  private_net:
    internal: true # Air-gap for the CLI tools
