services:
  gateway:
    build: ../gateway
    stop_grace_period: 5s
    volumes:
      - ../gateway/squid.conf:/etc/squid/squid.conf:ro
    networks:
      - public_net
      - private_net

  claude-code: &cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args: &build_args
        CURRENT_HOME: ${CURRENT_HOME}
        CURRENT_USERNAME: ${CURRENT_USERNAME}
        CURRENT_UID: ${CURRENT_UID}
        CURRENT_GID: ${CURRENT_GID}
        INSTALL_COMMAND: npm install -g @anthropic-ai/claude-code
    profiles: ["cli"] # prevents auto-start with docker compose up
    networks:
      - private_net
    environment:
      https_proxy: http://gateway:3128
      http_proxy: http://gateway:3128
    depends_on:
      - gateway

  codex:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: npm install -g @openai/codex

  gemini:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_CMD: npm install -g @google/gemini-cli

  cline:
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: |-
          npm install -g cline
          npm install -g kanban

  opencode:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: curl -fsSL https://opencode.ai/install | bash

  aider:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: pip install aider-chat

  goose:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash

  pi:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: npm install -g --ignore-scripts @earendil-works/pi-coding-agent

  prime-agent:
    <<: *cli_tool
    build:
      context: .
      dockerfile: common.Dockerfile
      args:
        <<: *build_args
        INSTALL_COMMAND: curl -fsSL https://app.primeintellect.ai/prime-agent/install.sh | sh

networks:
  public_net:
    driver: bridge
  private_net:
    internal: true # Air-gap for the CLI tools
